### ISSUE TITLE
Maps: Custom GeoJson Support in Region Maps

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/geospatial#122]
**Is your feature request related to a problem? Please describe.**
Ability to provide custom GeoJson to have custom vector maps.

**Describe the solution you'd like**
Should be able to upload GeoJson files and use them in the regional Maps dashboard.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by junqiu-lei** [comment]
Since related PRs merged to geospatial and dashboards-maps repos for 2.2.0 release, going to close this issue.
