### ISSUE TITLE
[FEATURE] Enable test with-security for geospatial in opensearch-build 

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/geospatial#148]
**Is your feature request related to a problem?**
Geospatial plugin is not enabled for test with-security in opensearch-build

**What solution would you like?**
Enable test with-security for Geospatial  in opensearch-build when opensearch-2.4.0-test.yml is ready
See an example for [opensearch-2.3.0-test.yml](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-2.3.0-test.yml#L91) 

**Do you have any additional context?**
Support for test with-security in Geospatial was added recently. https://github.com/opensearch-project/geospatial/pull/138
During 2.4 release, we need to enable it in opensearch-build package.

**Comment by VijayanB** [comment]
@heemin32 can this be closed?

**Comment by heemin32** [comment]
Not yet. opensearch-2.4.0-test.yml is not ready.
@peterzhuamazon when will the file be ready?

**Comment by peterzhuamazon** [comment]
> Not yet. opensearch-2.4.0-test.yml is not there yet. @peterzhuamazon when will the file be ready?

I will add this next week as our build just get stabled a bit. Not fully ready.

**Comment by heemin32** [comment]
It is enabled. https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.4.0/opensearch-2.4.0-test.yml#L102
