### ISSUE TITLE
[RFC] - Support GeoJson Point type format in GeoPoint and XYPoint field

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/geospatial#152]
Update: It will be mostly just GeoJson Point type format support for both GeoPoint and XYPoint. There won't be code sharing between GeoPoint and XYPoint implementation to reduce code duplication as it requires OpenSearch core package to have awareness of geospatial plugin which is not ideal.

-----

The purpose of this RFC (request for comments) is to gather community feedback on a new proposal to support `GeoJson` Point type format in `GeoPoint` and `XYPoint` field.

Related issue https://github.com/opensearch-project/OpenSearch/issues/3775

# GeoJson Point Type
Point type in `GeoJson` is one of `GeoJson` type which is used to represent a single position. Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates):
```
{
   "type": "Point",
   "coordinates": [41.12, -71.34]
}
```

# Indexing
Below is an example of indexing `GeoPoint` and `XYPoint` field using `GeoJson` Point type format

## GeoPoint
Point expressed as a `GeoJson` Point object.
```
PUT indexing_geopoint
{
  "mappings": {
    "properties": {
      "point": {
        "type": "geo_point"
      }
    }
  }
}

PUT indexing_geopoint/_doc/1
{
  "text": "Point as an object using GeoJSON format",
  "point": { 
    "type": "Point",
    "coordinates": [41.12, -71.34]
  }
}
```
## XYPoint
Point expressed as a `GeoJson` Point object.
```
PUT indexing_xypoint
{
  "mappings": {
    "properties": {
      "geometry": {
        "type": "xy_point"
      }
    }
  }
}

PUT indexing_xypoint/_doc/1
{
  "text": "Point as an object using GeoJSON format",
  "geometry": { 
    "type": "Point",
    "coordinates": [41.12, -71.34]
  }
}
```

# Implementation
## Current
`XYPointFieldType` and `GeoPointFieldType` has `PointParser`. When generating `PointParser` instance, it passes function parameter using a static method in `XYPointParser` and `GeoUtils` respectively. `PointParser` has parsing logic to handle the outer part of contents and the static method in `XYPointParser` and `GeoUtils` has parsing logic of each format for a point. The static methods in `GeoUtils` and `XYPointParser` have duplicated logic in them.

<img width="1099" alt="Screen Shot 2022-09-15 at 12 48 47 PM" src="https://user-images.githubusercontent.com/1809492/190506612-550510fb-9acc-47dc-b558-f5ce02bf14c0.png">

## Proposal
We will introduce a PointUtils which will have a parsing method for each types which are common for both GeoPoint and XYPoint: Object, GeoJson, and Array. GeoUtils and XYPointParser will have the top level parsing logic and calls PointUtils to handle final data format.

This will remove code duplication between GeoUtils and XYPointParser. This approach also minimize the code change required compared to the other alternatives. 

Red box in the following diagram indicate either modified or newly created classes.
<img width="1122" alt="Screen Shot 2022-09-20 at 4 17 55 PM" src="https://user-images.githubusercontent.com/1809492/191383536-b596d262-e713-40aa-98fb-7eb03f5de16e.png">

# Alternatives
## 1. Adds common point parser class
We will introduce a new CommonPointParser class. CommonPointParser will have the top level parsing logic which is generic to any point type. The CommonPointParser will delegate all type specific tasks to methods of which GeoPointParser and XYPointParser will override.

This change will reduce duplicated code in XYPoint type parser and GeoPoint type parser. However, one of the comments that I received is that GeoUtils having dependency on GeoPointParser doesn’t look right. Also, during implementation, this approach makes the code more complex than the proposed option without gaining much in reducing code duplication.

Red box in the following diagram represent either modified or newly created classes. 

<img width="1101" alt="Screen Shot 2022-09-15 at 12 49 14 PM" src="https://user-images.githubusercontent.com/1809492/191383718-f7c164cb-c373-46ec-bf7f-5a6984a37bac.png">

## 2. Adds GeoJson Point type parsing logic in both GeoUtils and XYPointParser

We can just modify existing parsing method in each of GeoUtils and XYPointParser to parse GeoJson point type. Even if the logic of parsing GeoJson is simple, it takes same mount of code change as proposed approach to embed the logic in existing parsing logic.
<img width="1139" alt="Screen Shot 2022-09-20 at 4 23 47 PM" src="https://user-images.githubusercontent.com/1809492/191383596-7de67bb2-ba3d-469e-a372-369a08b3c0d8.png">

## 3. Use existing GeoJson or GeoJsonParser

We could reuse existing `GeoJson` class or `GeoJsonParser` class to parse `GeoJson` point type. However, Current implementation in `GeoJson` class and `GeoJsonParser` class parse any type of GeoJson format. Therefore, we cannot fail fast when the data is not `GeoJson` Point type which is the only `GeoJson` type we are going to support. There is no separate method only to parse `GeoJson` Point type in those classes as well. Also, the code duplication issue will remain same as before because other parsing logics will stay in `GeoUtils` and `XYPointParser`.

<img width="1142" alt="Screen Shot 2022-09-15 at 1 11 58 PM" src="https://user-images.githubusercontent.com/1809492/190507478-b6defc38-f229-4e59-8843-01ae66e3776c.png">

**Comment by aucoindan** [comment]
A couple of comments

1. I don't think GeoJSON fits within `XYPoint`. 

> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [[WGS84](https://www.rfc-editor.org/rfc/rfc7946#ref-WGS84)] datum, with longitude and latitude units of decimal degrees.

https://www.rfc-editor.org/rfc/rfc7946#section-4

Isn't the point of `XYPoint` to capture arbitrary x,y coordinate systems (e.g. non-spherical) that aren't bound within (-180.0000, -90.0000, 180.0000, 90.0000)? That _shouldn't_ be happening with GeoJSON objects. 

2. GeoJSON has an optional elevation/altitude element. 

> Altitude or elevation MAY be included as an optional third element.

https://www.rfc-editor.org/rfc/rfc7946#section-3

How will this third element be handled? Will an exception be thrown, will the "z" element just be dropped, or should `GeoPoint` be changed to accept a "z" element?

**Comment by heemin32** [comment]
@aucoindan Thanks for your valuable comments. Here are my answers.

**1. I don't think GeoJSON fits within XYPoint.**
You are correct if we are going to represent XYPoint in GeoJson format. However here, we are going to allow customer to use GeoJson format to insert XYPoint data. In other words, converting xy point to geo point is invalid but converting geo point to xy point is valid.

**2. GeoJSON has an optional elevation/altitude element.**
This is true for Array format as well. There is an option during index creation if you want to ignore or throw error when there is the third element in the data. This option will apply to GeoJson data as well.
