### ISSUE TITLE
Upload API should accepts any valid index name as input

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/geospatial#183]
Upload API accepts requests only when index name ends with -map. This was added because api was initially planned to call only by Region maps. With Maps from 2.5, the upload API should allow user to upload any valid GeoJSON with any acceptable valid index name ( no mandatory suffix ). This won't affect Region maps, since front end already have this validation in place.

**Comment by heemin32** [comment]
_This won't affect Region maps, since front end already have this validation in place._

Is that mean, we need such restriction for Region map? We cannot rely on frontend validation. Customer request can hit the backend directly.

**Comment by navneet1v** [comment]
@VijayanB The description poses 2 questions:
1. For region maps do need maps as suffix on the index name?
2. With 2.5 release of dashboard are we thinking that a valid geojson can be applied apart from region maps?

I would like to understand that more and then check the PR.

and +1 on @heemin32 comment, we need to have validations at both the places.

**Comment by VijayanB** [comment]
For question 2, yes, you can use it in cluster and document layers

**Comment by navneet1v** [comment]
@VijayanB I think it make sense, but as region maps older UI will also be supported in 2.5 release the check on the OSD will still remain. We need to make sure that we are removing that check also in this case.

**Comment by heemin32** [comment]
Is there other ways to identify index that was created by file upload without using the suffix now?

**Comment by VijayanB** [comment]
Sorry it was not clear from description. Let me try to explain how it is handled now. From OpenSearch Dashboards 2.3 onwards, region map will call this API by adding suffix "-map" as index name. For ex: if user gives test-index, then OSD sends index name as test-index-map as input name. In the backend, this input is validated for suffix. This was added as extra validation to make sure that this API is used only for Region Maps. This "-map" suffix is  required so that region map can ask list of index that ends with "-map" and suggest only those index for custom vector map. 

Now, we can leverage the same API to create an index for non-Region map use cases . Hence, i am proposing to remove this check only from backend. We still have to add "-map" suffix from OSD for Region map for older UI in-order to be available for Custom Vector Map.

What changed now with this change?
It was expected ( only supported ) that users will use OSD UI to upload Custom Vector Map .
Before this Change:
If they tried to do this from curl or non-dashboard, it will be rejected unless api includes expected suffix. 
After this change:
The request will be succeeded, since, this request can be used to create an index that can be used independent of Region Map. Here, we are successfully decoupling backend API from OSD requirements.

IMO, i don't think this breaks any backward compatibility. 
@navneet1v @heemin32 Please let me know wdyt and do you have any other suggestions?

**Comment by heemin32** [comment]
Thanks @VijayanB. It is clear for me now. Agree that we can remove the validation in backend side.

One more question. In the new release, I assume we have another way to get a list of Custom Vector Map without relying on the "-map" suffix?

**Comment by VijayanB** [comment]
> 

We are taking a different direction where going forward customer can use any index with geospatial field types as custom vector map

**Comment by heemin32** [comment]
The needs to remove the validation from backend side is clear as it needs to be used by cases other than Custom Vector Map. 

We should have a better way to track a group of indices in OSD without relying on suffix. @VijayanB, could you create an issue in dashboards-maps repo?

**Comment by VijayanB** [comment]
Feature is merged.
