### ISSUE TITLE
[BUG] Flaky Test failure GeoTileGridIT.testGeoShapes

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/geospatial#212]
@mch2 commented on [Fri Jan 27 2023](https://github.com/opensearch-project/OpenSearch/issues/6054)

```
REPRODUCE WITH: ./gradlew ':modules:geo:internalClusterTest' --tests "org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes" -Dtests.seed=DCE20E20A42AFD34 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=und -Dtests.timezone=America/Yakutat -Druntime.java=19

org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT > testGeoShapes FAILED
    java.lang.AssertionError: Geotile 3/7/4 has wrong doc count  expected:<46> but was:<1>
        at __randomizedtesting.SeedInfo.seed([DCE20E20A42AFD34:365FB6EF2B56AE29]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes(GeoTileGridIT.java:78)
```

https://build.ci.opensearch.org/job/gradle-check/10078/consoleFull
https://github.com/opensearch-project/OpenSearch/pull/5898#issuecomment-1407128379

---

@mch2 commented on [Mon Jan 30 2023](https://github.com/opensearch-project/OpenSearch/issues/6054#issuecomment-1408988632)

https://build.ci.opensearch.org/job/gradle-check/10076/

**Comment by minalsha** [comment]
assigning it to geospatial team to help triage

**Comment by navneet1v** [comment]
Does the rerun of this test results in failure too?

**Comment by heemin32** [comment]
I was able to reproduce the failure with JAVA19. The test passed with JAVA17 and JAVA18.

**Comment by heemin32** [comment]
Still investigating. It is not related with JAVA version but with a seed of random values.

**Comment by heemin32** [comment]
Test is failing when bounding box filtering option is provided. The failure could happen when multiple shapes belong to a single tile and bounding box filters part of them.

When we calculate the expected number of document for a tile, we do it without any filtering. https://github.com/opensearch-project/OpenSearch/blob/b1cf2d144ebac899bcae9880ee51728df397b5c0/modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java#L98-L102

If bounding box is provided, it might filter some of the document and the number of document in response could be less than what we calculated before for the tile.

**Comment by navneet1v** [comment]
Found the issue, the first problem is here: https://github.com/opensearch-project/OpenSearch/blob/b1cf2d144ebac899bcae9880ee51728df397b5c0/modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java#L91-L96 , there is double if condition added. Seems like a copy paste error to me. 

1 more thing, which is an edge case, we don't need to compute buckets for shapes for a given precision if they are outside the BB. This can also cause issues if the bucket and BB is intersecting the bucket at corners. Will fix this also.

**Comment by navneet1v** [comment]
@minalsha raised this PR: https://github.com/opensearch-project/OpenSearch/pull/6120, please check the PR . Once this is approved. the tests will be consistent.

**Comment by navneet1v** [comment]
The PR is merged. Closing the github issue.
