### ISSUE TITLE
[BUG] The repo is undescribed

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/geospatial#4]
**Describe the bug**
This repo lacks a description

**Other plugins installed**
N/a

**To Reproduce**
1. Go to https://github.com/opensearch-project/geospatial/ in any browser
2. Look to the right, a little down from the top of the page
3. Instead of a user friendly description, you'll see something like this:

<img width="319" alt="Screen Shot 2021-08-16 at 3 35 40 PM" src="https://user-images.githubusercontent.com/1152927/129619850-c06d4003-68a5-4f04-848f-17c8aeb0b24c.png">

**Expected behavior**
To see a one-line description of what this repo does.

**Screenshots**
See above

**Comment by CEHENKLE** [comment]
I've added "Provides OpenSearch geospatial features" to the description.  Please reopen if you've got something else you want to see there :)

**Comment by stockholmux** [comment]
@CEHENKLE I'm not sure that provides more value than the name itself :) 

What features does it provide?

**Comment by CEHENKLE** [comment]
Confirmed with Vamshi that this is mostly placeholder for now.  Confirmed "Future home of GeoSpatial features for OpenSearch" with Eli, and updated.
