### ISSUE TITLE
About GeoIP processor

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/geospatial#41]
Hi,

i would like to ask some clarification about GeoIP processor.
In particular, is there some update mechanism for the database?
If not, how would it be possible to update (maybe using scripts)? Did someone already tried to do this?

Thank you

Pietro

**Comment by CEHENKLE** [comment]
@opensearch-project/geospatial Hey folks - I chatted with @nknize about this, and we didn't pick up geoip work when we forked.  It seems like something that the folks on this repo could dig into. 

Thanks,
/C

**Comment by navneet1v** [comment]
This seems to be a feature request. Please do +1 if you need this feature to be priortized.

**Comment by sempervictus** [comment]
GeoIP resolution is a rather critical element in security-relevant pipelines such as that used by Wazuh and various network monitoring solutions (flow analysis and such). Would very much aid in easing migration from pre-licensing-nonsense ES.

**Comment by heemin32** [comment]
We started working on this feature. https://github.com/opensearch-project/OpenSearch/issues/5856

**Comment by heemin32** [comment]
New IP2Geo processor is launched. https://opensearch.org/docs/latest/api-reference/ingest-apis/processors/ip2geo/
Closing the issue now.

**Comment by sempervictus** [comment]
Thank you
