### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/geospatial#94]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @vamshin @VijayanB can you please post an update on this branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by navneet1v** [comment]
@prudhvigodithi The branching strategy has been implemented, I can see main pointing to 3.0. We don't have 1.x branches as this repo was not launched at that time. Please provide details what else is missing.

**Comment by navneet1v** [comment]
@VijayanB can you please check if there is any action item left on this?

**Comment by VijayanB** [comment]
Following core's branching strategy. No action is required.

**Comment by dblock** [comment]
Could you please double-check that:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by navneet1v** [comment]
Tasks completed

- [X]  main is building 3.0
- [X]  2.x is building next 2.x, which is currently 2.4.0
- [ ]  2.3 is building next 2.3, which is 2.3.1
- [ ]  manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by navneet1v** [comment]
As per the latest update, 2.3.1 release is not happening. So I won't do the version update. Will work on adding this repo in the 3.0 and 2.4 manifest files.

**Comment by navneet1v** [comment]
PR https://github.com/opensearch-project/opensearch-build/pull/2675
