### ISSUE TITLE
New XYPoint Field to index and query documents that contains cartesian points

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/geospatial#95]
The new `xy_point` field type facilitates the indexing and searching of points represented as unit less x, y pairs that fall in a 2-dimensional planar coordinate system. This will be similar to geo_point field type but there are no range limitations (geo_point has a range limitation of -90 to 90 for latitude and -180 to 180 for longitude). The point field will be based on Lucene field type [XYPoint](https://lucene.apache.org/core/8_5_1/core/org/apache/lucene/geo/XYPoint.html)

RFC - https://github.com/opensearch-project/geospatial/issues/90

**Comment by VijayanB** [comment]
Feature is merged into 2.x
